# Copyright 2026 EPAM Systems, Inc. ("EPAM")
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


import json
from unittest.mock import MagicMock

import pytest

from codemie.agents.tools.interactive.request_user_input import RequestUserInputTool
from codemie.core.a2ui import adapter
from codemie.core.a2ui import envelopes as wire, catalog


def _format_catalog_description():
    """The catalog's own description, generated by the SDK — the authoritative contract."""
    return catalog.format_().prompt_generator.catalog_description(include_schema=True)


BASIC_CATALOG_COMPONENTS = {
    "Text",
    "Image",
    "Icon",
    "Video",
    "AudioPlayer",
    "Row",
    "Column",
    "List",
    "Card",
    "Tabs",
    "Modal",
    "Divider",
    "Button",
    "TextField",
    "CheckBox",
    "ChoicePicker",
    "Slider",
    "DateTimeInput",
}


class TestCatalog:
    def test_catalog_id_is_the_official_v0_9_basic_catalog(self):
        # 0.9.1 is a patch of the v0_9 spec family; the renderer (@a2ui/react v0_9)
        # declares the v0_9 URL, so the backend must advertise the same string.
        assert catalog.CATALOG_ID == "https://a2ui.org/specification/v0_9/catalogs/basic/catalog.json"

    def test_component_names_cover_the_full_basic_catalog(self):
        assert set(catalog.component_names()) == BASIC_CATALOG_COMPONENTS

    def test_validator_accepts_a_minimal_valid_surface(self):
        components = [
            {"id": "root", "component": "Column", "children": ["greeting"]},
            {"id": "greeting", "component": "Text", "text": "Hello"},
        ]
        envelopes = adapter.build_surface_envelopes("surf-ok", components)
        assert catalog.validate_envelopes(envelopes) == []

    def test_validation_error_names_the_offending_component(self):
        """The raw SDK error buries the cause under every branch of the message `oneOf`.

        Seen live, a ChoicePicker option carrying an unknown property produced eight lines
        including "'deleteSurface' is a required property" and "Additional properties are
        not allowed ('updateComponents' was unexpected)" — all about message shapes that
        were never in play. Both the user and, on its next turn, the model read this.
        """
        components = [
            {"id": "root", "component": "Column", "children": ["pick"]},
            {
                "id": "pick",
                "component": "ChoicePicker",
                "label": "Modules",
                "value": {"path": "/modules"},
                "options": [{"label": "SSO", "value": "sso", "disabled": True}],
            },
        ]
        errors = catalog.validate_envelopes(adapter.build_surface_envelopes("s", components))
        joined = " ".join(errors)
        assert "'pick'" in joined, "the error must say which component failed"
        assert "ChoicePicker" in joined
        # Naming the component is not enough: a model told only that its ChoicePicker is
        # wrong repeated the same surface three turns running. The offending property is
        # nested in an option, and it is read out of the catalog, not hand-listed.
        assert "options[0].disabled" in joined, "the error must name the property the catalog lacks"
        for noise in ("deleteSurface", "updateDataModel", "createSurface"):
            assert noise not in joined, f"error still carries the irrelevant {noise} branch"

    def test_valid_component_reports_no_unknown_properties(self):
        """The hint must stay silent when the component is merely wrong some other way."""
        components = [
            {"id": "root", "component": "Column", "children": ["pick"]},
            {"id": "pick", "component": "ChoicePicker", "label": "Modules", "value": {"path": "/m"}},
        ]
        joined = " ".join(catalog.validate_envelopes(adapter.build_surface_envelopes("s", components)))
        assert "does not define" not in joined

    def test_validator_rejects_unknown_component_type(self):
        envelopes = adapter.build_surface_envelopes("surf-bad", [{"id": "root", "component": "NotARealComponent"}])
        errors = catalog.validate_envelopes(envelopes)
        assert errors, "unknown component type must produce validation errors"

    def test_prompt_section_carries_the_component_contract(self):
        """Without the catalog schema the model has no idea what a component looks like.

        Observed live: the prompt described the components abstractly, the model fell back
        to the legacy protocol shape ({"type": "textinput"}) and every surface was rejected.
        """
        section = catalog.render_prompt_section()
        for name in ("TextField", "ChoicePicker", "Button", "DateTimeInput"):
            assert name in section, f"prompt must document the {name} component"
        assert '"component"' in section, "prompt must show the component discriminator key"

    def test_prompt_example_is_a_surface_the_tool_would_accept(self):
        """The worked example must survive the very validation it teaches.

        An example that does not validate would train models to produce rejected surfaces,
        which is worse than having no example at all — so it goes through the real
        validator and the real emission bounds, exactly like an agent-authored surface.
        """
        envelopes = adapter.build_surface_envelopes("example", catalog.EXAMPLE_SURFACE)
        assert catalog.validate_envelopes(envelopes) == []
        assert catalog.render_prompt_section().count('"id": "root"') >= 1

    def test_prompt_example_is_answerable(self):
        """It must also carry a submit control, the rule the role description states."""
        RequestUserInputTool(thread_generator=MagicMock()).execute(components=catalog.EXAMPLE_SURFACE)

    def test_prompt_example_binds_its_input_to_the_data_model(self):
        """The one thing the example is load-bearing for: `value` as a binding, not a literal.

        Removing the example produced surfaces whose every input carried a literal value
        (`3`, `false`, `[]`). Those are schema-valid — `value` accepts either form — and
        completely dead: nothing writes back, so the form renders and cannot be filled in.
        The example is what shows which form an input needs, so an example that stopped
        demonstrating it would be worse than useless.
        """
        inputs = [
            component
            for component in catalog.EXAMPLE_SURFACE
            if component["component"] in ("TextField", "ChoicePicker", "Slider", "CheckBox", "DateTimeInput")
        ]
        assert inputs, "the example must show at least one input"
        for component in inputs:
            value = component.get("value")
            assert isinstance(value, dict) and "path" in value, (
                f"example input {component['id']!r} carries a literal value; "
                "that is what taught models to emit unbindable forms"
            )

    def test_prompt_describes_components_only_through_the_catalog(self):
        """Nothing about components may be authored by us — the catalog is the contract.

        Hand-written prose describing components would be a second spec that drifts from
        the catalog the renderer and validator actually use, which is precisely the
        maintenance cost this migration exists to remove. So the section must be exactly
        our transport text, a catalog-valid example, and the catalog's own description.
        """
        section = catalog.render_prompt_section()
        remainder = section
        for authored in (
            catalog._ROLE_DESCRIPTION,
            catalog._TRANSPORT_DESCRIPTION,
            "A complete, valid `components` argument:",
            json.dumps(catalog.EXAMPLE_SURFACE, indent=2),
            _format_catalog_description(),
        ):
            assert authored in remainder, "prompt lost one of its declared parts"
            remainder = remainder.replace(authored, "", 1)
        assert not remainder.strip(), f"prompt carries text from no declared source: {remainder[:200]!r}"

    def test_prompt_section_describes_the_tool_transport_only(self):
        """The SDK's own prompt tells the model to emit <a2ui-json> blocks in its reply.

        This backend delivers surfaces as a tool call and builds the envelopes itself, so
        that boilerplate is a contradictory instruction and must not reach the model.
        """
        section = catalog.render_prompt_section()
        assert "a2ui-json" not in section
        assert "request_user_input" in section


class TestValidateActionEnvelope:
    """Client->server `action` envelope structural validation.

    The SDK ships no client_to_server JSON schema asset for 0.9.1 and its pydantic
    models pin version "v0.9" with all fields required, so the backend validates the
    documented v0.9.1 wire contract structurally (extras forbidden, like the SDK).
    """

    def _envelope(self, **action_overrides):
        action = {
            "name": "submit",
            "surfaceId": "s1",
            "sourceComponentId": "ok",
            "timestamp": "2026-08-10T00:00:00Z",
            "context": {"email": "a@b.c"},
        }
        action.update(action_overrides)
        return {"version": "v0.9.1", "action": action}

    def test_full_valid_envelope_accepted(self):
        assert catalog.validate_action_envelope(self._envelope()) == []

    def test_minimal_envelope_accepted(self):
        # sourceComponentId / timestamp / context are optional on our wire.
        envelope = {"version": "v0.9.1", "action": {"name": "cancel", "surfaceId": "s9"}}
        assert catalog.validate_action_envelope(envelope) == []

    def test_v0_9_version_also_accepted(self):
        envelope = self._envelope()
        envelope["version"] = "v0.9"
        assert catalog.validate_action_envelope(envelope) == []

    def test_non_dict_envelope_rejected(self):
        assert catalog.validate_action_envelope(["not", "a", "dict"])
        assert catalog.validate_action_envelope(None)

    def test_missing_action_rejected(self):
        assert catalog.validate_action_envelope({"version": "v0.9.1"})

    def test_missing_name_rejected(self):
        envelope = {"version": "v0.9.1", "action": {"surfaceId": "s1"}}
        assert catalog.validate_action_envelope(envelope)

    def test_missing_surface_id_rejected(self):
        envelope = {"version": "v0.9.1", "action": {"name": "submit"}}
        assert catalog.validate_action_envelope(envelope)

    def test_wrong_types_rejected(self):
        assert catalog.validate_action_envelope(self._envelope(name=123))
        assert catalog.validate_action_envelope(self._envelope(surfaceId=[]))
        assert catalog.validate_action_envelope(self._envelope(context="not-a-dict"))

    def test_unsupported_version_rejected(self):
        envelope = self._envelope()
        envelope["version"] = "v2.0"
        assert catalog.validate_action_envelope(envelope)

    def test_extra_envelope_key_rejected(self):
        envelope = self._envelope()
        envelope["catalogId"] = "attacker-catalog"
        assert catalog.validate_action_envelope(envelope)

    def test_extra_action_key_rejected(self):
        # Anti-tampering: catalog identity is resolved server-side from the stored
        # surface; a smuggled catalogId (or any unknown key) must be rejected.
        assert catalog.validate_action_envelope(self._envelope(catalogId="attacker-catalog"))


class TestErrorsNameTheCause:
    """A refused surface must say what is wrong in the component's own vocabulary.

    The reader is the user and, on its next turn, the model — neither can act on a bare
    "does not match the catalog", and the turn ends either way, so the one error emitted
    has to carry the whole diagnosis.
    """

    @staticmethod
    def _errors(component):
        surface = [{"id": "root", "component": "Column", "children": ["go"]}, component]
        pruned, _ = catalog.prune_to_catalog([dict(c) for c in surface])
        return catalog.validate_envelopes(adapter.build_surface_envelopes("s", pruned), root_id="root")

    def test_names_the_missing_required_property(self):
        """`label` on a Button is dropped as unknown; the real fault is the absent `child`.

        Pruning removes the property the validator would otherwise have complained about,
        so without naming what is REQUIRED the error would name nothing at all.
        """
        errors = self._errors(
            {"id": "go", "component": "Button", "label": "Send", "action": {"event": {"name": "submit"}}}
        )
        assert errors and "requires ['child']" in errors[0]

    def test_names_undefined_properties_when_they_survive_to_validation(self):
        errors = catalog.validate_envelopes(
            adapter.build_surface_envelopes(
                "s",
                [
                    {"id": "root", "component": "Column", "children": ["t"]},
                    {"id": "t", "component": "Text", "text": "hi", "nonsense": 1},
                ],
            ),
            root_id="root",
        )
        assert errors and "does not define ['nonsense']" in errors[0]

    def test_does_not_quote_the_message_oneof_branches(self):
        """One bad component makes jsonschema report every message kind it tried."""
        errors = self._errors({"id": "go", "component": "Button", "action": {"event": {"name": "x"}}})
        assert errors
        assert "deleteSurface" not in errors[0] and "createSurface" not in errors[0]


class TestGatedOptions:
    """An option the agent marked unavailable must not become available by being pruned.

    `disabled` is not in the Basic Catalog, and pruning an unknown property is normally
    meaning-preserving — the gate is the one case where it is meaning-REVERSING: the
    option comes back selectable, and because the stored surface no longer records the
    gate, the intake finds the value among those the surface offered and confirms the
    answer as legitimate.
    """

    @staticmethod
    def _picker(options):
        return [
            {"id": "root", "component": "Column", "children": ["pick", "send"]},
            {
                "id": "pick",
                "component": "ChoicePicker",
                "label": "Plan",
                "value": {"path": "/plan"},
                "options": options,
            },
            {"id": "send", "component": "Button", "child": "label", "action": {"event": {"name": "submit"}}},
            {"id": "label", "component": "Text", "text": "Send"},
        ]

    def test_a_gated_option_is_removed_not_ungated(self):
        pruned, dropped = catalog.prune_to_catalog(
            self._picker(
                [
                    {"label": "Free", "value": "free"},
                    {"label": "Enterprise", "value": "enterprise", "disabled": True},
                ]
            )
        )
        picker = next(c for c in pruned if c["id"] == "pick")
        assert [option["value"] for option in picker["options"]] == ["free"]
        assert "pick.options[enterprise]" in dropped

    def test_the_server_then_refuses_that_value(self):
        """The point of removing it: the surface no longer offers it, so an answer fails."""
        from codemie.service.conversation.a2ui_intake import unanswerable_seed_paths

        pruned, _ = catalog.prune_to_catalog(
            self._picker(
                [
                    {"label": "Free", "value": "free"},
                    {"label": "Enterprise", "value": "enterprise", "disabled": True},
                ]
            )
        )
        envelopes = adapter.build_surface_envelopes("s", pruned)
        assert unanswerable_seed_paths(envelopes, {"plan": ["enterprise"]}) == ["plan"]
        assert unanswerable_seed_paths(envelopes, {"plan": ["free"]}) == []

    def test_an_ungated_surface_is_untouched(self):
        options = [{"label": "Free", "value": "free"}, {"label": "Pro", "value": "pro"}]
        pruned, dropped = catalog.prune_to_catalog(self._picker(options))
        picker = next(c for c in pruned if c["id"] == "pick")
        assert picker["options"] == options
        assert dropped == []

    def test_a_picker_with_everything_gated_is_refused(self):
        """Removing every option leaves a question with no answer — worth saying so.

        The catalog puts no minimum on `options`, so an empty picker validates and would
        reach the user as a question they cannot answer at all.
        """
        from codemie.agents.tools.interactive.request_user_input import RequestUserInputTool

        pruned, _ = catalog.prune_to_catalog(
            self._picker([{"label": "Enterprise", "value": "enterprise", "disabled": True}])
        )
        with pytest.raises(ValueError, match="offers no options"):
            RequestUserInputTool(thread_generator=MagicMock()).execute(components=pruned)


class TestWireVocabulary:
    """The message kind names live in config.py, so the v1.0 rename has one site."""

    def test_only_the_wire_module_spells_out_the_message_kinds(self):
        import pathlib

        root = pathlib.Path(__file__).resolve().parents[3] / "src" / "codemie"
        offenders = []
        for path in root.rglob("*.py"):
            if path.name == "config.py":
                continue  # the vocabulary module itself
            text = path.read_text()
            # Only real accesses count — prose in a docstring may name a message kind.
            for kind in ("createSurface", "updateComponents", "updateDataModel", "deleteSurface"):
                for shape in (f'["{kind}"]', f'.get("{kind}")', f'"{kind}":'):
                    if shape in text:
                        offenders.append(f"{path.name}: {shape}")
        assert not offenders, f"wire names spelled out outside config.py: {offenders}"

    def test_components_are_read_back_out_of_the_envelopes(self):
        envelopes = adapter.build_surface_envelopes(
            "s",
            [
                {"id": "root", "component": "Column", "children": ["t"]},
                {"id": "t", "component": "Text", "text": "hi"},
            ],
        )
        assert [c["id"] for c in wire.components_of(envelopes)] == ["root", "t"]

    def test_a_detail_path_resolves_to_the_component_it_blames(self):
        envelopes = adapter.build_surface_envelopes("s", [{"id": "root", "component": "Column", "children": []}])
        assert wire.component_at(envelopes, "updateComponents.components.0")["id"] == "root"
        assert wire.component_at(envelopes, "createSurface.catalogId") is None
        assert wire.component_at(envelopes, "updateComponents.components.99") is None


class TestAdapter:
    def test_surface_envelopes_shape_and_order(self):
        components = [{"id": "root", "component": "Text", "text": "Hi"}]
        envelopes = adapter.build_surface_envelopes("surf-1", components)

        assert [next(k for k in e if k != "version") for e in envelopes] == [
            "createSurface",
            "updateComponents",
        ]
        create, update = envelopes
        assert create["createSurface"]["surfaceId"] == "surf-1"
        assert create["createSurface"]["catalogId"] == catalog.CATALOG_ID
        assert update["updateComponents"]["surfaceId"] == "surf-1"
        assert update["updateComponents"]["components"] == components

    def test_surface_envelopes_validate_against_sdk_wire_schema(self):
        components = [{"id": "root", "component": "Text", "text": "Hi"}]
        envelopes = adapter.build_surface_envelopes("surf-1", components)
        assert catalog.validate_envelopes(envelopes) == []

    def test_data_model_envelope_is_appended_when_provided(self):
        envelopes = adapter.build_surface_envelopes(
            "surf-2",
            [{"id": "root", "component": "Text", "text": "Hi"}],
            data_model={"name": "value"},
        )
        kinds = [next(k for k in e if k != "version") for e in envelopes]
        assert kinds[-1] == "updateDataModel"
        assert catalog.validate_envelopes(envelopes) == []
